# Generated by Django 4.0.5 on 2022-06-13 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackLog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='capacity',
            field=models.IntegerField(default=1000),
        ),
    ]
