# Generated by Django 4.0.5 on 2022-06-13 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BackLog', '0003_warehouse_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={},
        ),
    ]
